name: CI

env:
  VERSION: '0.0.1'

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: checkout files
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          uses: docker/login-action@v1
          username: ${{ secrets.CRED_USER_DOCKER }}
          password: ${{ secrets.CRED_USER_PWD }}
          push: true
          platforms: linux/amd64,linux/arm/v8
          tags: |
            ${{ secrets.CRED_USER_DOCKER }}/alertservice:latest
